import java.util.*;
/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

// Use XOR to solve
public class L389FindtheDifference {
	public class Solution {
        public char findTheDifference(String s, String t) {
            char[] arr1 = new char[s.length()+t.length()];
            String total = s+t;
            arr1 = total.toCharArray();
            int find = 0;
            for(char c : arr1){
                find = c ^ find;
            }
            char ans = (char) (find);
            return ans;
        }
	}
    public static void main(String[] args) throws Exception {
    	
    }
}
